### ISSUE TITLE
Sharing AOC assets

### ISSUE THREAD

**Issue by playsenge** [scyence2k/AoC2024#1]
As it is stated on adventofcode.com/2024/about

"Can I copy/redistribute part of Advent of Code? Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar."

Remove the .txt files with data

**Comment by scyence2k** [comment]
My apologies.

I removed them from the repo but they are still visible in the commit history. Any way to remove that?

**Comment by playsenge** [comment]
I made the same mistake in my repo so idk, I guess just don't add more and we should be fine
